# Generated by Django 2.2.7 on 2019-12-03 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommintegration',
            name='bigcommerce_status',
            field=models.BooleanField(blank=True, choices=[(0, 'OK'), (1, 'Not OK')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ecommintegration',
            name='shopify_status',
            field=models.BooleanField(blank=True, choices=[(0, 'OK'), (1, 'Not OK')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ecommintegration',
            name='woocommerce_status',
            field=models.BooleanField(blank=True, choices=[(0, 'OK'), (1, 'Not OK')], default=None, null=True),
        ),
    ]
