# Generated by Django 2.2.7 on 2019-12-03 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_auto_20191203_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecommintegration',
            name='retailer_status',
            field=models.BooleanField(default=True),
        ),
    ]
