# Generated by Django 2.2.7 on 2019-12-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='complete_at',
            field=models.DateTimeField(blank=True, default=None, verbose_name='complete_at'),
        ),
    ]
