# Generated by Django 2.2.7 on 2019-12-02 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191202_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='complete_at',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='complete_at'),
        ),
    ]
