# Generated by Django 2.2.7 on 2019-12-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191202_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='test_report',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.SmallIntegerField(choices=[(0, ''), (1, 'Passed'), (2, 'Failed'), (3, 'Running')], default=0),
        ),
    ]
